
// Generated by Cadence Genus(TM) Synthesis Solution 21.14-s082_1
// Generated on: Dec  4 2024 16:29:27 IST (Dec  4 2024 10:59:27 UTC)

// Verification Directory fv/barrel_s 

module barrel_s(in, ctrl, dir, out);
  input [7:0] in;
  input [2:0] ctrl;
  input dir;
  output [7:0] out;
  wire [7:0] in;
  wire [2:0] ctrl;
  wire dir;
  wire [7:0] out;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_56, n_58, n_60, n_62, n_64, n_66, n_68;
  oai221d1 g1628__2398(.A (n_54), .B1 (n_37), .B2 (n_68), .C1 (n_58),
       .C2 (n_64), .ZN (out[5]));
  oai221d1 g1630__5107(.A (n_48), .B1 (n_32), .B2 (n_68), .C1 (n_56),
       .C2 (n_66), .ZN (out[6]));
  oai221d1 g1629__6260(.A (n_51), .B1 (n_42), .B2 (n_68), .C1 (n_62),
       .C2 (n_66), .ZN (out[7]));
  oai221d1 g1627__4319(.A (n_52), .B1 (n_46), .B2 (n_66), .C1 (n_60),
       .C2 (n_64), .ZN (out[4]));
  oai221d1 g1631__8428(.A (n_53), .B1 (n_44), .B2 (n_66), .C1 (n_62),
       .C2 (n_64), .ZN (out[1]));
  oai221d1 g1632__5526(.A (n_50), .B1 (n_60), .B2 (n_66), .C1 (n_34),
       .C2 (n_68), .ZN (out[2]));
  oai221d1 g1633__6783(.A (n_45), .B1 (n_58), .B2 (n_66), .C1 (n_40),
       .C2 (n_68), .ZN (out[3]));
  oai221d1 g1634__3680(.A (n_55), .B1 (n_49), .B2 (n_66), .C1 (n_56),
       .C2 (n_64), .ZN (out[0]));
  inv0d0 g1643(.I (n_33), .ZN (n_55));
  inv0d0 g1635(.I (n_41), .ZN (n_54));
  inv0d0 g1642(.I (n_43), .ZN (n_53));
  inv0d0 g1637(.I (n_35), .ZN (n_52));
  inv0d0 g1636(.I (n_38), .ZN (n_51));
  aoim22d1 g1645__1617(.A1 (n_27), .A2 (n_47), .B1 (n_49), .B2 (n_64),
       .Z (n_50));
  aoim22d1 g1640__2802(.A1 (n_31), .A2 (n_47), .B1 (n_46), .B2 (n_64),
       .Z (n_48));
  aoim22d1 g1646__1705(.A1 (n_29), .A2 (n_47), .B1 (n_44), .B2 (n_64),
       .Z (n_45));
  oai22d1 g1644__5122(.A1 (n_42), .A2 (n_39), .B1 (n_28), .B2 (n_68),
       .ZN (n_43));
  oai22d1 g1638__8246(.A1 (n_40), .A2 (n_39), .B1 (n_36), .B2 (n_66),
       .ZN (n_41));
  oai22d1 g1639__7098(.A1 (n_37), .A2 (n_39), .B1 (n_36), .B2 (n_64),
       .ZN (n_38));
  oai22d1 g1641__6131(.A1 (n_34), .A2 (n_39), .B1 (n_30), .B2 (n_68),
       .ZN (n_35));
  oai22d1 g1647__1881(.A1 (n_32), .A2 (n_39), .B1 (n_26), .B2 (n_68),
       .ZN (n_33));
  inv0d0 g1648(.I (n_30), .ZN (n_31));
  inv0d0 g1657(.I (n_28), .ZN (n_29));
  inv0d0 g1658(.I (n_26), .ZN (n_27));
  nr02d0 g1649__5115(.A1 (n_24), .A2 (n_19), .ZN (n_40));
  nr02d0 g1666__7482(.A1 (n_25), .A2 (n_20), .ZN (n_56));
  nr02d0 g1650__4733(.A1 (n_25), .A2 (n_22), .ZN (n_30));
  nr02d0 g1651__6161(.A1 (n_24), .A2 (n_14), .ZN (n_36));
  nr02d0 g1665__9315(.A1 (n_23), .A2 (n_16), .ZN (n_32));
  nr02d0 g1652__9945(.A1 (n_15), .A2 (n_12), .ZN (n_58));
  nr02d0 g1653__2883(.A1 (n_21), .A2 (n_10), .ZN (n_46));
  nr02d0 g1654__2346(.A1 (n_23), .A2 (n_22), .ZN (n_49));
  nr02d0 g1661__1666(.A1 (n_13), .A2 (n_17), .ZN (n_44));
  nr02d0 g1656__7410(.A1 (n_21), .A2 (n_20), .ZN (n_34));
  nr02d0 g1659__6417(.A1 (n_18), .A2 (n_19), .ZN (n_62));
  nr02d0 g1660__5477(.A1 (n_18), .A2 (n_17), .ZN (n_37));
  nr02d0 g1655__2398(.A1 (n_11), .A2 (n_16), .ZN (n_60));
  nr02d0 g1662__5107(.A1 (n_15), .A2 (n_14), .ZN (n_28));
  nr02d0 g1663__6260(.A1 (n_13), .A2 (n_12), .ZN (n_42));
  nr02d0 g1664__4319(.A1 (n_11), .A2 (n_10), .ZN (n_26));
  nr02d0 g1675__8428(.A1 (n_4), .A2 (ctrl[0]), .ZN (n_24));
  nr02d0 g1668__5526(.A1 (n_3), .A2 (ctrl[0]), .ZN (n_23));
  nr02d0 g1670__6783(.A1 (n_2), .A2 (n_9), .ZN (n_16));
  nr02d0 g1674__3680(.A1 (n_8), .A2 (n_9), .ZN (n_22));
  nr02d0 g1667__1617(.A1 (n_8), .A2 (ctrl[0]), .ZN (n_18));
  nr02d0 g1673__2802(.A1 (n_7), .A2 (ctrl[0]), .ZN (n_21));
  nr02d0 g1676__1705(.A1 (n_5), .A2 (ctrl[0]), .ZN (n_25));
  nr02d0 g1677__5122(.A1 (n_1), .A2 (ctrl[0]), .ZN (n_15));
  nr02d0 g1681__8246(.A1 (n_6), .A2 (n_9), .ZN (n_12));
  nr02d0 g1679__7098(.A1 (n_7), .A2 (n_9), .ZN (n_14));
  nr02d0 g1680__6131(.A1 (n_6), .A2 (ctrl[0]), .ZN (n_11));
  nr02d0 g1669__1881(.A1 (n_5), .A2 (n_9), .ZN (n_19));
  nr02d0 g1678__5115(.A1 (n_4), .A2 (n_9), .ZN (n_20));
  nr02d0 g1682__7482(.A1 (n_3), .A2 (n_9), .ZN (n_17));
  nr02d0 g1671__4733(.A1 (n_2), .A2 (ctrl[0]), .ZN (n_13));
  nr02d0 g1672__6161(.A1 (n_1), .A2 (n_9), .ZN (n_10));
  aoi22d1 g1685__9315(.A1 (n_0), .A2 (in[1]), .B1 (in[5]), .B2
       (ctrl[2]), .ZN (n_2));
  aoi22d1 g1684__9945(.A1 (n_0), .A2 (in[7]), .B1 (in[3]), .B2
       (ctrl[2]), .ZN (n_8));
  aoi22d1 g1683__2883(.A1 (n_0), .A2 (in[0]), .B1 (in[4]), .B2
       (ctrl[2]), .ZN (n_3));
  aoi22d1 g1686__2346(.A1 (n_0), .A2 (in[4]), .B1 (in[0]), .B2
       (ctrl[2]), .ZN (n_7));
  aoi22d1 g1689__1666(.A1 (n_0), .A2 (in[3]), .B1 (in[7]), .B2
       (ctrl[2]), .ZN (n_1));
  aoi22d1 g1688__7410(.A1 (n_0), .A2 (in[5]), .B1 (in[1]), .B2
       (ctrl[2]), .ZN (n_4));
  aoi22d1 g1687__6417(.A1 (n_0), .A2 (in[6]), .B1 (in[2]), .B2
       (ctrl[2]), .ZN (n_5));
  aoi22d1 g1690__5477(.A1 (n_0), .A2 (in[2]), .B1 (in[6]), .B2
       (ctrl[2]), .ZN (n_6));
  inv0d0 g1693(.I (n_47), .ZN (n_39));
  nr02d0 g1694__2398(.A1 (ctrl[1]), .A2 (dir), .ZN (n_47));
  nd12d0 g1691__5107(.A1 (dir), .A2 (ctrl[1]), .ZN (n_68)); 
  nd02d0 g1695__6260(.A1 (ctrl[1]), .A2 (dir), .ZN (n_64));
  nd12d0 g1692__4319(.A1 (ctrl[1]), .A2 (dir), .ZN (n_66));
  inv0d0 g1697(.I (ctrl[0]), .ZN (n_9));
  inv0d0 g1696(.I (ctrl[2]), .ZN (n_0));

pc3d01 Iin0(.PAD(in[0]),.CIN(in1[0]));
pc3d01 Iin1(.PAD(in[1]),.CIN(in1[1]));
pc3d01 Iin2(.PAD(in[2]),.CIN(in1[2]));
pc3d01 Iin3(.PAD(in[3]),.CIN(in1[3]));
pc3d01 Iin4(.PAD(in[4]),.CIN(in1[4]));
pc3d01 Iin5(.PAD(in[5]),.CIN(in1[5]));
pc3d01 Iin6(.PAD(in[6]),.CIN(in1[6]));
pc3d01 Iin7(.PAD(in[7]),.CIN(in1[7]));

pc3d01 Ictrl0(.PAD(ctrl[0]),.CIN(ctrl1[0]));
pc3d01 Ictrl1(.PAD(ctrl[1]),.CIN(ctrl1[1]));
pc3d01 Ictrl2(.PAD(ctrl[2]),.CIN(ctrl1[2]));

pc3d01 Idir(.PAD(dir),.CIN(dir1));

pc3d01 out0(.PAD(out[0]),.CIN(out1[0]));
pc3d01 out1(.PAD(out[1]),.CIN(out1[1]));
pc3d01 out2(.PAD(out[2]),.CIN(out1[2]));
pc3d01 out3(.PAD(out[3]),.CIN(out1[3]));
pc3d01 out4(.PAD(out[4]),.CIN(out1[4]));
pc3d01 out5(.PAD(out[5]),.CIN(out1[5]));
pc3d01 out6(.PAD(out[6]),.CIN(out1[6]));
pc3d01 out7(.PAD(out[7]),.CIN(out1[7]));
endmodule

